-- Librería Quisqueya: estructura principal, relaciones y seguridad RLS.
-- Ejecutar una sola vez en Supabase SQL Editor antes del Script 02.

create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;

-- Usuarios y roles

create table if not exists public.roles (
    id smallint generated by default as identity primary key,
    codigo text not null unique check (codigo in ('cliente', 'empleado', 'administrador')),
    nombre text not null
);

create table if not exists public.perfiles (
    id uuid primary key references auth.users(id) on delete cascade,
    nombres text not null,
    apellidos text not null default '',
    telefono text,
    activo boolean not null default true,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now()
);

create table if not exists public.usuario_roles (
    usuario_id uuid primary key references public.perfiles(id) on delete cascade,
    rol_id smallint not null references public.roles(id),
    asignado_en timestamptz not null default now()
);

insert into public.roles (codigo, nombre)
values ('cliente', 'Cliente'), ('empleado', 'Empleado'), ('administrador', 'Administrador')
on conflict (codigo) do update set nombre = excluded.nombre;

-- Devuelve true solamente para cuentas con rol administrativo.
create or replace function private.es_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
          from public.usuario_roles ur
          join public.roles r on r.id = ur.rol_id
         where ur.usuario_id = auth.uid()
           and r.codigo = 'administrador'
    );
$$;

-- Permite operaciones a administradores y empleados.
create or replace function private.es_personal()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
          from public.usuario_roles ur
          join public.roles r on r.id = ur.rol_id
         where ur.usuario_id = auth.uid()
           and r.codigo in ('administrador', 'empleado')
    );
$$;

-- Crea el perfil y asigna el rol cliente al registrar una cuenta.
create or replace function private.crear_perfil_usuario()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.perfiles (id, nombres, apellidos)
    values (
        new.id,
        coalesce(
            nullif(btrim(new.raw_user_meta_data ->> 'nombres'), ''),
            split_part(coalesce(new.email, 'usuario'), '@', 1)
        ),
        coalesce(nullif(btrim(new.raw_user_meta_data ->> 'apellidos'), ''), '')
    )
    on conflict (id) do nothing;

    insert into public.usuario_roles (usuario_id, rol_id)
    select new.id, id from public.roles where codigo = 'cliente'
    on conflict (usuario_id) do nothing;

    return new;
end;
$$;

drop trigger if exists crear_perfil_al_registrar on auth.users;
create trigger crear_perfil_al_registrar
after insert on auth.users
for each row execute function private.crear_perfil_usuario();

-- Catálogo e inventario

create table if not exists public.autores (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    creado_en timestamptz not null default now()
);

create table if not exists public.categorias (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    activo boolean not null default true,
    creado_en timestamptz not null default now()
);

create table if not exists public.libros (
    id bigint generated by default as identity primary key,
    isbn text unique,
    titulo text not null,
    descripcion text not null default '',
    precio numeric(12,2) not null check (precio >= 0),
    formato text not null default 'fisico' check (formato in ('fisico', 'digital')),
    idioma text not null default 'Español',
    editorial text,
    categoria_id bigint references public.categorias(id) on delete set null,
    stock_minimo integer not null default 5 check (stock_minimo >= 0),
    imagen_portada text,
    activo boolean not null default true,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now()
);

create table if not exists public.libro_autor (
    libro_id bigint not null references public.libros(id) on delete cascade,
    autor_id bigint not null references public.autores(id) on delete restrict,
    primary key (libro_id, autor_id)
);

create table if not exists public.inventarios (
    libro_id bigint primary key references public.libros(id) on delete cascade,
    cantidad_existencia integer not null default 0 check (cantidad_existencia >= 0),
    cantidad_reservada integer not null default 0 check (
        cantidad_reservada >= 0 and cantidad_reservada <= cantidad_existencia
    ),
    cantidad_disponible integer generated always as
        (cantidad_existencia - cantidad_reservada) stored,
    actualizado_en timestamptz not null default now()
);

create table if not exists public.sucursales (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    direccion text not null,
    ciudad text not null,
    provincia text not null,
    telefono text,
    activo boolean not null default true,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now()
);

-- Carrito y pedidos

create table if not exists public.carritos (
    id uuid primary key default gen_random_uuid(),
    perfil_id uuid not null unique references public.perfiles(id) on delete cascade,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now()
);

create table if not exists public.carrito_detalles (
    carrito_id uuid not null references public.carritos(id) on delete cascade,
    libro_id bigint not null references public.libros(id) on delete cascade,
    cantidad integer not null check (cantidad between 1 and 999),
    agregado_en timestamptz not null default now(),
    primary key (carrito_id, libro_id)
);

create sequence if not exists public.pedidos_numero_seq;

create table if not exists public.pedidos (
    id uuid primary key default gen_random_uuid(),
    numero text not null unique default (
        'LQ-' || to_char(now(), 'YYYYMMDD') || '-' ||
        lpad(nextval('public.pedidos_numero_seq')::text, 6, '0')
    ),
    cliente_id uuid not null references public.perfiles(id) on delete restrict,
    cliente_nombre text not null,
    cliente_correo text not null,
    metodo_entrega text not null check (metodo_entrega in ('domicilio', 'retiro')),
    sucursal_id bigint references public.sucursales(id) on delete restrict,
    metodo_pago text not null check (metodo_pago in ('contra_entrega', 'transferencia')),
    estado text not null default 'pendiente' check (
        estado in ('pendiente', 'confirmado', 'procesando', 'listo_retiro',
                   'enviado', 'entregado', 'cancelado', 'devuelto')
    ),
    estado_pago text not null default 'pendiente' check (
        estado_pago in ('pendiente', 'verificando', 'pagado', 'rechazado', 'reembolsado')
    ),
    subtotal numeric(12,2) not null check (subtotal >= 0),
    costo_envio numeric(12,2) not null default 0 check (costo_envio >= 0),
    total numeric(12,2) not null check (total = subtotal + costo_envio),
    notas text,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now(),
    check (
        (metodo_entrega = 'retiro' and sucursal_id is not null) or
        (metodo_entrega = 'domicilio' and sucursal_id is null)
    )
);

create table if not exists public.pedido_detalles (
    id bigint generated by default as identity primary key,
    pedido_id uuid not null references public.pedidos(id) on delete cascade,
    libro_id bigint not null references public.libros(id) on delete restrict,
    isbn text,
    titulo text not null,
    precio_unitario numeric(12,2) not null check (precio_unitario >= 0),
    cantidad integer not null check (cantidad between 1 and 999),
    subtotal numeric(12,2) generated always as (precio_unitario * cantidad) stored,
    unique (pedido_id, libro_id)
);

create table if not exists public.pedido_direcciones_entrega (
    pedido_id uuid primary key references public.pedidos(id) on delete cascade,
    destinatario text not null,
    telefono text not null,
    linea_1 text not null,
    linea_2 text,
    sector text,
    ciudad text not null,
    provincia text not null,
    codigo_postal text,
    referencia text
);

create table if not exists public.movimientos_inventario (
    id bigint generated by default as identity primary key,
    libro_id bigint not null references public.libros(id) on delete restrict,
    pedido_id uuid references public.pedidos(id) on delete restrict,
    realizado_por uuid references public.perfiles(id) on delete set null,
    tipo text not null check (tipo in ('entrada', 'ajuste', 'reserva', 'liberacion', 'salida', 'devolucion')),
    cambio_existencia integer not null default 0,
    cambio_reservada integer not null default 0,
    motivo text not null,
    creado_en timestamptz not null default now(),
    check (cambio_existencia <> 0 or cambio_reservada <> 0)
);

create table if not exists public.mensajes_contacto (
    id uuid primary key default gen_random_uuid(),
    perfil_id uuid not null references public.perfiles(id) on delete cascade,
    nombre text not null,
    correo text not null,
    telefono text,
    motivo text not null,
    mensaje text not null check (char_length(btrim(mensaje)) >= 10),
    estado text not null default 'nuevo' check (estado in ('nuevo', 'en_revision', 'respondido', 'cerrado')),
    creado_en timestamptz not null default now()
);

-- Índices usados por el catálogo, los pedidos y las políticas.
create index if not exists libros_activos_titulo_idx on public.libros (activo, titulo);
create index if not exists pedidos_cliente_fecha_idx on public.pedidos (cliente_id, creado_en desc);
create index if not exists pedidos_estado_fecha_idx on public.pedidos (estado, creado_en desc);
create index if not exists pedido_detalles_pedido_idx on public.pedido_detalles (pedido_id);
create index if not exists mensajes_perfil_fecha_idx on public.mensajes_contacto (perfil_id, creado_en desc);

-- Políticas de seguridad RLS

alter table public.roles enable row level security;
alter table public.perfiles enable row level security;
alter table public.usuario_roles enable row level security;
alter table public.autores enable row level security;
alter table public.categorias enable row level security;
alter table public.libros enable row level security;
alter table public.libro_autor enable row level security;
alter table public.inventarios enable row level security;
alter table public.sucursales enable row level security;
alter table public.carritos enable row level security;
alter table public.carrito_detalles enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_detalles enable row level security;
alter table public.pedido_direcciones_entrega enable row level security;
alter table public.movimientos_inventario enable row level security;
alter table public.mensajes_contacto enable row level security;

drop policy if exists roles_lectura_autenticada on public.roles;
create policy roles_lectura_autenticada on public.roles
for select to authenticated using (true);

drop policy if exists perfiles_lectura on public.perfiles;
create policy perfiles_lectura on public.perfiles
for select to authenticated using (id = auth.uid() or private.es_admin());

drop policy if exists perfiles_actualizacion_propia on public.perfiles;
create policy perfiles_actualizacion_propia on public.perfiles
for update to authenticated using (id = auth.uid()) with check (id = auth.uid());

drop policy if exists roles_usuario_lectura on public.usuario_roles;
create policy roles_usuario_lectura on public.usuario_roles
for select to authenticated using (usuario_id = auth.uid() or private.es_admin());

drop policy if exists autores_lectura on public.autores;
create policy autores_lectura on public.autores
for select to authenticated using (true);

drop policy if exists categorias_lectura on public.categorias;
create policy categorias_lectura on public.categorias
for select to authenticated using (activo or private.es_personal());

drop policy if exists libros_lectura on public.libros;
create policy libros_lectura on public.libros
for select to authenticated using (activo or private.es_personal());

drop policy if exists libro_autor_lectura on public.libro_autor;
create policy libro_autor_lectura on public.libro_autor
for select to authenticated using (true);

drop policy if exists inventario_lectura on public.inventarios;
create policy inventario_lectura on public.inventarios
for select to authenticated using (
    private.es_personal() or exists (
        select 1 from public.libros l where l.id = libro_id and l.activo
    )
);

drop policy if exists sucursales_lectura on public.sucursales;
create policy sucursales_lectura on public.sucursales
for select to authenticated using (activo or private.es_admin());

drop policy if exists carritos_lectura on public.carritos;
create policy carritos_lectura on public.carritos
for select to authenticated using (perfil_id = auth.uid() or private.es_admin());

drop policy if exists carritos_creacion on public.carritos;
create policy carritos_creacion on public.carritos
for insert to authenticated with check (perfil_id = auth.uid());

drop policy if exists carritos_actualizacion on public.carritos;
create policy carritos_actualizacion on public.carritos
for update to authenticated using (perfil_id = auth.uid()) with check (perfil_id = auth.uid());

drop policy if exists carritos_eliminacion on public.carritos;
create policy carritos_eliminacion on public.carritos
for delete to authenticated using (perfil_id = auth.uid());

drop policy if exists carrito_detalles_lectura on public.carrito_detalles;
create policy carrito_detalles_lectura on public.carrito_detalles
for select to authenticated using (
    exists (select 1 from public.carritos c where c.id = carrito_id and c.perfil_id = auth.uid())
    or private.es_admin()
);

drop policy if exists carrito_detalles_creacion on public.carrito_detalles;
create policy carrito_detalles_creacion on public.carrito_detalles
for insert to authenticated with check (
    exists (select 1 from public.carritos c where c.id = carrito_id and c.perfil_id = auth.uid())
);

drop policy if exists carrito_detalles_actualizacion on public.carrito_detalles;
create policy carrito_detalles_actualizacion on public.carrito_detalles
for update to authenticated
using (exists (select 1 from public.carritos c where c.id = carrito_id and c.perfil_id = auth.uid()))
with check (exists (select 1 from public.carritos c where c.id = carrito_id and c.perfil_id = auth.uid()));

drop policy if exists carrito_detalles_eliminacion on public.carrito_detalles;
create policy carrito_detalles_eliminacion on public.carrito_detalles
for delete to authenticated using (
    exists (select 1 from public.carritos c where c.id = carrito_id and c.perfil_id = auth.uid())
);

drop policy if exists pedidos_lectura on public.pedidos;
create policy pedidos_lectura on public.pedidos
for select to authenticated using (cliente_id = auth.uid() or private.es_personal());

drop policy if exists pedidos_actualizacion_admin on public.pedidos;
create policy pedidos_actualizacion_admin on public.pedidos
for update to authenticated using (private.es_personal()) with check (private.es_personal());

drop policy if exists pedido_detalles_lectura on public.pedido_detalles;
create policy pedido_detalles_lectura on public.pedido_detalles
for select to authenticated using (
    exists (
        select 1 from public.pedidos p
         where p.id = pedido_id and (p.cliente_id = auth.uid() or private.es_personal())
    )
);

drop policy if exists direcciones_pedido_lectura on public.pedido_direcciones_entrega;
create policy direcciones_pedido_lectura on public.pedido_direcciones_entrega
for select to authenticated using (
    exists (
        select 1 from public.pedidos p
         where p.id = pedido_id and (p.cliente_id = auth.uid() or private.es_personal())
    )
);

drop policy if exists movimientos_lectura_admin on public.movimientos_inventario;
create policy movimientos_lectura_admin on public.movimientos_inventario
for select to authenticated using (private.es_personal());

drop policy if exists mensajes_creacion_propia on public.mensajes_contacto;
create policy mensajes_creacion_propia on public.mensajes_contacto
for insert to authenticated with check (perfil_id = auth.uid());

drop policy if exists mensajes_lectura on public.mensajes_contacto;
create policy mensajes_lectura on public.mensajes_contacto
for select to authenticated using (perfil_id = auth.uid() or private.es_admin());

drop policy if exists mensajes_actualizacion_admin on public.mensajes_contacto;
create policy mensajes_actualizacion_admin on public.mensajes_contacto
for update to authenticated using (private.es_admin()) with check (private.es_admin());

-- Permisos de API

revoke all on schema private from public, anon;
revoke all on public.roles, public.perfiles, public.usuario_roles,
              public.autores, public.categorias, public.libros, public.libro_autor,
              public.inventarios, public.sucursales,
              public.carritos, public.carrito_detalles,
              public.pedidos, public.pedido_detalles,
              public.pedido_direcciones_entrega,
              public.movimientos_inventario, public.mensajes_contacto
from anon, authenticated;
revoke all on sequence public.pedidos_numero_seq from anon, authenticated;

grant usage on schema public to authenticated;
grant usage on schema private to authenticated;
grant execute on function private.es_admin() to authenticated;
grant execute on function private.es_personal() to authenticated;

grant select on public.roles, public.perfiles, public.usuario_roles to authenticated;
grant select on public.autores, public.categorias, public.libros, public.libro_autor,
                public.inventarios, public.sucursales to authenticated;
grant select, insert, update, delete on public.carritos, public.carrito_detalles to authenticated;
grant select, update (estado_pago) on public.pedidos to authenticated;
grant select on public.pedido_detalles, public.pedido_direcciones_entrega to authenticated;
grant select on public.movimientos_inventario to authenticated;
grant select, insert, update (estado) on public.mensajes_contacto to authenticated;

revoke all on function private.es_admin() from public, anon;
revoke all on function private.es_personal() from public, anon;
revoke all on function private.crear_perfil_usuario() from public, anon, authenticated;
