-- Base de datos de Libreria Quisqueya

-- Ejecutar una sola vez en un proyecto nuevo de Supabase.



begin;



create extension if not exists pgcrypto with schema extensions;
create schema if not exists private;

-- Usuarios y roles

create table if not exists public.roles (
    id smallint generated by default as identity primary key,
    codigo text not null unique check (codigo in ('cliente', 'empleado', 'administrador')),
    nombre text not null
);

create table if not exists public.perfiles (
    id uuid primary key references auth.users(id) on delete cascade,
    nombres text not null,
    apellidos text not null default '',
    telefono text,
    activo boolean not null default true,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now()
);

create table if not exists public.usuario_roles (
    usuario_id uuid primary key references public.perfiles(id) on delete cascade,
    rol_id smallint not null references public.roles(id),
    asignado_en timestamptz not null default now()
);

insert into public.roles (codigo, nombre)
values ('cliente', 'Cliente'), ('empleado', 'Empleado'), ('administrador', 'Administrador')
on conflict (codigo) do update set nombre = excluded.nombre;

-- Devuelve true solamente para cuentas con rol administrativo.
create or replace function private.es_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
          from public.usuario_roles ur
          join public.roles r on r.id = ur.rol_id
          join public.perfiles p on p.id = ur.usuario_id
         where ur.usuario_id = auth.uid()
           and r.codigo = 'administrador'
           and p.activo = true
    );
$$;

-- Permite operaciones a administradores y empleados.
create or replace function private.es_personal()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
    select exists (
        select 1
          from public.usuario_roles ur
          join public.roles r on r.id = ur.rol_id
          join public.perfiles p on p.id = ur.usuario_id
         where ur.usuario_id = auth.uid()
           and r.codigo in ('administrador', 'empleado')
           and p.activo = true
    );
$$;

-- Crea el perfil y asigna el rol cliente al registrar una cuenta.
create or replace function private.crear_perfil_usuario()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    insert into public.perfiles (id, nombres, apellidos)
    values (
        new.id,
        coalesce(
            nullif(btrim(new.raw_user_meta_data ->> 'nombres'), ''),
            split_part(coalesce(new.email, 'usuario'), '@', 1)
        ),
        coalesce(nullif(btrim(new.raw_user_meta_data ->> 'apellidos'), ''), '')
    )
    on conflict (id) do nothing;

    insert into public.usuario_roles (usuario_id, rol_id)
    select new.id, id from public.roles where codigo = 'cliente'
    on conflict (usuario_id) do nothing;

    return new;
end;
$$;

drop trigger if exists crear_perfil_al_registrar on auth.users;
create trigger crear_perfil_al_registrar
after insert on auth.users
for each row execute function private.crear_perfil_usuario();

-- Catálogo e inventario

create table if not exists public.autores (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    creado_en timestamptz not null default now()
);

create table if not exists public.categorias (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    activo boolean not null default true,
    creado_en timestamptz not null default now()
);

create table if not exists public.libros (
    id bigint generated by default as identity primary key,
    isbn text unique,
    titulo text not null,
    descripcion text not null default '',
    precio numeric(12,2) not null check (precio >= 0),
    descuento_pct numeric(5,2) not null default 0 check (descuento_pct between 0 and 100),
    formato text not null default 'fisico' check (formato in ('fisico', 'digital')),
    idioma text not null default 'Español',
    editorial text,
    categoria_id bigint references public.categorias(id) on delete set null,
    stock_minimo integer not null default 5 check (stock_minimo >= 0),
    imagen_portada text,
    activo boolean not null default true,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now()
);

create table if not exists public.libro_autor (
    libro_id bigint not null references public.libros(id) on delete cascade,
    autor_id bigint not null references public.autores(id) on delete restrict,
    primary key (libro_id, autor_id)
);

create table if not exists public.inventarios (
    libro_id bigint primary key references public.libros(id) on delete cascade,
    cantidad_existencia integer not null default 0 check (cantidad_existencia >= 0),
    cantidad_reservada integer not null default 0 check (
        cantidad_reservada >= 0 and cantidad_reservada <= cantidad_existencia
    ),
    cantidad_disponible integer generated always as
        (cantidad_existencia - cantidad_reservada) stored,
    actualizado_en timestamptz not null default now()
);

create table if not exists public.sucursales (
    id bigint generated by default as identity primary key,
    nombre text not null unique,
    direccion text not null,
    ciudad text not null,
    provincia text not null,
    telefono text,
    activo boolean not null default true,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now()
);

-- Carrito y pedidos

create table if not exists public.carritos (
    id uuid primary key default gen_random_uuid(),
    perfil_id uuid not null unique references public.perfiles(id) on delete cascade,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now()
);

create table if not exists public.carrito_detalles (
    carrito_id uuid not null references public.carritos(id) on delete cascade,
    libro_id bigint not null references public.libros(id) on delete cascade,
    cantidad integer not null check (cantidad between 1 and 999),
    agregado_en timestamptz not null default now(),
    primary key (carrito_id, libro_id)
);

create sequence if not exists public.pedidos_numero_seq;

create table if not exists public.pedidos (
    id uuid primary key default gen_random_uuid(),
    numero text not null unique default (
        'LQ-' || to_char(now(), 'YYYYMMDD') || '-' ||
        lpad(nextval('public.pedidos_numero_seq')::text, 6, '0')
    ),
    cliente_id uuid not null references public.perfiles(id) on delete restrict,
    cliente_nombre text not null,
    cliente_correo text not null,
    cliente_documento text,
    cliente_telefono text,
    metodo_entrega text not null check (metodo_entrega in ('domicilio', 'retiro')),
    sucursal_id bigint references public.sucursales(id) on delete restrict,
    metodo_pago text not null check (metodo_pago in ('contra_entrega', 'efectivo', 'tarjeta', 'transferencia')),
    estado text not null default 'pendiente' check (
        estado in ('pendiente', 'confirmado', 'procesando', 'listo_retiro',
                   'enviado', 'entregado', 'cancelado', 'devuelto')
    ),
    estado_pago text not null default 'pendiente' check (
        estado_pago in ('pendiente', 'verificando', 'pagado', 'rechazado', 'reembolsado')
    ),
    subtotal numeric(12,2) not null check (subtotal >= 0),
    descuento numeric(12,2) not null default 0 check (descuento >= 0 and descuento <= subtotal),
    costo_envio numeric(12,2) not null default 0 check (costo_envio >= 0),
    total numeric(12,2) not null check (total = subtotal - descuento + costo_envio),
    notas text,
    creado_en timestamptz not null default now(),
    actualizado_en timestamptz not null default now(),
    check (
        (metodo_entrega = 'retiro' and sucursal_id is not null) or
        (metodo_entrega = 'domicilio' and sucursal_id is null)
    )
);

create table if not exists public.pedido_detalles (
    id bigint generated by default as identity primary key,
    pedido_id uuid not null references public.pedidos(id) on delete cascade,
    libro_id bigint not null references public.libros(id) on delete restrict,
    isbn text,
    titulo text not null,
    precio_unitario numeric(12,2) not null check (precio_unitario >= 0),
    cantidad integer not null check (cantidad between 1 and 999),
    descuento_pct numeric(5,2) not null default 0 check (descuento_pct between 0 and 100),
    subtotal numeric(12,2) generated always as (precio_unitario * cantidad) stored,
    descuento numeric(12,2) generated always as (round(precio_unitario * cantidad * descuento_pct / 100, 2)) stored,
    total_linea numeric(12,2) generated always as (precio_unitario * cantidad - round(precio_unitario * cantidad * descuento_pct / 100, 2)) stored,
    unique (pedido_id, libro_id)
);

create table if not exists public.pedido_direcciones_entrega (
    pedido_id uuid primary key references public.pedidos(id) on delete cascade,
    destinatario text not null,
    telefono text not null,
    linea_1 text not null,
    linea_2 text,
    sector text,
    ciudad text not null,
    provincia text not null,
    codigo_postal text,
    referencia text
);

create table if not exists public.movimientos_inventario (
    id bigint generated by default as identity primary key,
    libro_id bigint not null references public.libros(id) on delete restrict,
    pedido_id uuid references public.pedidos(id) on delete restrict,
    realizado_por uuid references public.perfiles(id) on delete set null,
    tipo text not null check (tipo in ('entrada', 'ajuste', 'reserva', 'liberacion', 'salida', 'devolucion')),
    cambio_existencia integer not null default 0,
    cambio_reservada integer not null default 0,
    motivo text not null,
    creado_en timestamptz not null default now(),
    check (cambio_existencia <> 0 or cambio_reservada <> 0)
);

create sequence if not exists public.cotizaciones_numero_seq;
create sequence if not exists public.facturas_numero_seq;

insert into public.sucursales (nombre, direccion, ciudad, provincia)
values ('Sucursal Principal', 'Direccion por configurar', 'Santo Domingo', 'Distrito Nacional')
on conflict (nombre) do nothing;

create table if not exists public.contact_messages (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references public.perfiles(id) on delete set null,
    nombre text not null check (char_length(btrim(nombre)) >= 3),
    correo text not null check (correo ~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'),
    telefono text,
    asunto text not null check (char_length(btrim(asunto)) >= 3),
    mensaje text not null check (char_length(btrim(mensaje)) >= 10),
    estado text not null default 'pendiente'
        check (estado in ('pendiente', 'leido', 'respondido', 'archivado')),
    created_at timestamptz not null default now()
);

create table if not exists public.configuracion_negocio (
    id smallint primary key default 1 check (id = 1),
    nombre_comercial text not null default 'Libreria Quisqueya',
    razon_social text not null default 'Libreria Quisqueya',
    eslogan text,
    rnc text,
    direccion text,
    ciudad text,
    provincia text,
    pais text not null default 'Republica Dominicana',
    telefono text,
    correo text,
    sitio_web text,
    logo_url text not null default 'assets/logo-quisqueya-profesional.png',
    atendido_por_default text,
    cotizacion_prefijo text not null default 'COT',
    cotizacion_validez_dias integer not null default 15 check (cotizacion_validez_dias between 1 and 365),
    cotizacion_tiempo_entrega text,
    cotizacion_condiciones text,
    cotizacion_notas text,
    cotizacion_mostrar_itbis boolean not null default true,
    cotizacion_itbis_pct numeric(5,2) not null default 18 check (cotizacion_itbis_pct between 0 and 100),
    factura_prefijo text not null default 'FAC',
    factura_condicion_pago text not null default 'contado' check (factura_condicion_pago in ('contado', 'credito')),
    factura_dias_credito integer not null default 30 check (factura_dias_credito between 1 and 365),
    factura_condiciones text,
    factura_notas text,
    factura_mostrar_itbis boolean not null default true,
    factura_itbis_pct numeric(5,2) not null default 18 check (factura_itbis_pct between 0 and 100),
    actualizado_por uuid references public.perfiles(id) on delete set null,
    actualizado_en timestamptz not null default now()
);

insert into public.configuracion_negocio (id)
values (1)
on conflict (id) do nothing;

create table if not exists public.cotizaciones (
    id uuid primary key default gen_random_uuid(),
    numero text not null unique,
    pedido_id uuid not null unique references public.pedidos(id) on delete restrict,
    cliente_id uuid not null references public.perfiles(id) on delete restrict,
    fecha_emision date not null default current_date,
    valida_hasta date not null,
    estado text not null default 'emitida' check (estado in ('emitida', 'aceptada', 'vencida', 'anulada')),
    subtotal numeric(12,2) not null check (subtotal >= 0),
    descuento numeric(12,2) not null default 0 check (descuento >= 0),
    itbis numeric(12,2) not null default 0 check (itbis >= 0),
    total numeric(12,2) not null check (total >= 0),
    snapshot jsonb not null,
    creado_por uuid references public.perfiles(id) on delete set null,
    creado_en timestamptz not null default now()
);

create table if not exists public.facturas (
    id uuid primary key default gen_random_uuid(),
    numero text not null unique,
    pedido_id uuid not null unique references public.pedidos(id) on delete restrict,
    cliente_id uuid not null references public.perfiles(id) on delete restrict,
    ncf text,
    fecha_emision date not null default current_date,
    fecha_vencimiento date,
    condicion_pago text not null check (condicion_pago in ('contado', 'credito')),
    estado text not null default 'emitida' check (estado in ('emitida', 'pagada', 'anulada')),
    subtotal numeric(12,2) not null check (subtotal >= 0),
    descuento numeric(12,2) not null default 0 check (descuento >= 0),
    itbis numeric(12,2) not null default 0 check (itbis >= 0),
    total numeric(12,2) not null check (total >= 0),
    snapshot jsonb not null,
    creado_por uuid references public.perfiles(id) on delete set null,
    creado_en timestamptz not null default now()
);

create unique index if not exists facturas_ncf_unico
on public.facturas (ncf)
where ncf is not null;

create index if not exists cotizaciones_cliente_fecha
on public.cotizaciones (cliente_id, creado_en desc);

create index if not exists facturas_cliente_fecha
on public.facturas (cliente_id, creado_en desc);

create index if not exists libros_activos_titulo_idx on public.libros (activo, titulo);
create index if not exists libros_categoria_idx on public.libros (categoria_id);
create index if not exists pedidos_cliente_fecha_idx on public.pedidos (cliente_id, creado_en desc);
create index if not exists pedidos_estado_fecha_idx on public.pedidos (estado, creado_en desc);
create index if not exists pedido_detalles_pedido_idx on public.pedido_detalles (pedido_id);
create index if not exists movimientos_libro_fecha_idx on public.movimientos_inventario (libro_id, creado_en desc);
create index if not exists movimientos_fecha_idx on public.movimientos_inventario (creado_en desc);
create index if not exists contact_messages_user_fecha_idx on public.contact_messages (user_id, created_at desc);
create index if not exists contact_messages_estado_fecha_idx on public.contact_messages (estado, created_at desc);

alter table public.roles enable row level security;
alter table public.perfiles enable row level security;
alter table public.usuario_roles enable row level security;
alter table public.autores enable row level security;
alter table public.categorias enable row level security;
alter table public.libros enable row level security;
alter table public.libro_autor enable row level security;
alter table public.inventarios enable row level security;
alter table public.sucursales enable row level security;
alter table public.carritos enable row level security;
alter table public.carrito_detalles enable row level security;
alter table public.pedidos enable row level security;
alter table public.pedido_detalles enable row level security;
alter table public.pedido_direcciones_entrega enable row level security;
alter table public.movimientos_inventario enable row level security;
alter table public.contact_messages enable row level security;
alter table public.configuracion_negocio enable row level security;
alter table public.cotizaciones enable row level security;
alter table public.facturas enable row level security;

create policy roles_lectura_autenticada on public.roles for select to authenticated using (true);
create policy perfiles_lectura on public.perfiles for select to authenticated using (id = auth.uid() or private.es_admin());
create policy perfiles_actualizacion_propia on public.perfiles for update to authenticated using (id = auth.uid()) with check (id = auth.uid());
create policy roles_usuario_lectura on public.usuario_roles for select to authenticated using (usuario_id = auth.uid() or private.es_admin());
create policy autores_lectura on public.autores for select to authenticated using (true);
create policy categorias_lectura on public.categorias for select to authenticated using (activo or private.es_personal());
create policy libros_lectura on public.libros for select to authenticated using (activo or private.es_personal());
create policy libro_autor_lectura on public.libro_autor for select to authenticated using (true);
create policy inventario_lectura on public.inventarios for select to authenticated using (
    private.es_personal() or exists (select 1 from public.libros l where l.id = libro_id and l.activo)
);
create policy sucursales_lectura on public.sucursales for select to authenticated using (activo or private.es_admin());
create policy carritos_lectura on public.carritos for select to authenticated using (perfil_id = auth.uid() or private.es_admin());
create policy carritos_creacion on public.carritos for insert to authenticated with check (perfil_id = auth.uid());
create policy carritos_actualizacion on public.carritos for update to authenticated using (perfil_id = auth.uid()) with check (perfil_id = auth.uid());
create policy carritos_eliminacion on public.carritos for delete to authenticated using (perfil_id = auth.uid());
create policy carrito_detalles_lectura on public.carrito_detalles for select to authenticated using (
    exists (select 1 from public.carritos c where c.id = carrito_id and c.perfil_id = auth.uid()) or private.es_admin()
);
create policy carrito_detalles_creacion on public.carrito_detalles for insert to authenticated with check (
    exists (select 1 from public.carritos c where c.id = carrito_id and c.perfil_id = auth.uid())
);
create policy carrito_detalles_actualizacion on public.carrito_detalles for update to authenticated
using (exists (select 1 from public.carritos c where c.id = carrito_id and c.perfil_id = auth.uid()))
with check (exists (select 1 from public.carritos c where c.id = carrito_id and c.perfil_id = auth.uid()));
create policy carrito_detalles_eliminacion on public.carrito_detalles for delete to authenticated using (
    exists (select 1 from public.carritos c where c.id = carrito_id and c.perfil_id = auth.uid())
);
create policy pedidos_lectura on public.pedidos for select to authenticated using (cliente_id = auth.uid() or private.es_personal());
create policy pedidos_actualizacion_personal on public.pedidos for update to authenticated using (private.es_personal()) with check (private.es_personal());
create policy pedido_detalles_lectura on public.pedido_detalles for select to authenticated using (
    exists (select 1 from public.pedidos p where p.id = pedido_id and (p.cliente_id = auth.uid() or private.es_personal()))
);
create policy direcciones_pedido_lectura on public.pedido_direcciones_entrega for select to authenticated using (
    exists (select 1 from public.pedidos p where p.id = pedido_id and (p.cliente_id = auth.uid() or private.es_personal()))
);
create policy movimientos_lectura_personal on public.movimientos_inventario for select to authenticated using (private.es_personal());
create policy contact_messages_lectura on public.contact_messages for select to authenticated using (user_id = auth.uid() or private.es_admin());
create policy contact_messages_actualizar_admin on public.contact_messages for update to authenticated using (private.es_admin()) with check (private.es_admin());
create policy configuracion_lectura on public.configuracion_negocio for select to authenticated using (true);
create policy cotizaciones_lectura on public.cotizaciones for select to authenticated using (cliente_id = auth.uid() or private.es_personal());
create policy facturas_lectura on public.facturas for select to authenticated using (cliente_id = auth.uid() or private.es_personal());

create policy autores_lectura_publica on public.autores for select to anon using (true);
create policy categorias_lectura_publica on public.categorias for select to anon using (activo);
create policy libros_lectura_publica on public.libros for select to anon using (activo);
create policy libro_autor_lectura_publica on public.libro_autor for select to anon using (
    exists (select 1 from public.libros l where l.id = libro_id and l.activo)
);
create policy inventario_lectura_publica on public.inventarios for select to anon using (
    exists (select 1 from public.libros l where l.id = libro_id and l.activo)
);

revoke all on schema private from public, anon;
revoke all on public.roles, public.perfiles, public.usuario_roles, public.autores,
    public.categorias, public.libros, public.libro_autor, public.inventarios,
    public.sucursales, public.carritos, public.carrito_detalles, public.pedidos,
    public.pedido_detalles, public.pedido_direcciones_entrega,
    public.movimientos_inventario, public.contact_messages,
    public.configuracion_negocio, public.cotizaciones, public.facturas
from anon, authenticated;
revoke all on sequence public.pedidos_numero_seq, public.cotizaciones_numero_seq,
    public.facturas_numero_seq from anon, authenticated;

grant usage on schema public to anon, authenticated;
grant usage on schema private to authenticated;
grant execute on function private.es_admin() to authenticated;
grant execute on function private.es_personal() to authenticated;
grant select on public.roles, public.perfiles, public.usuario_roles to authenticated;
grant select on public.autores, public.categorias, public.libros, public.libro_autor,
    public.inventarios, public.sucursales to authenticated;
grant select, insert, update, delete on public.carritos, public.carrito_detalles to authenticated;
grant select on public.pedidos, public.pedido_detalles, public.pedido_direcciones_entrega,
    public.movimientos_inventario, public.contact_messages, public.configuracion_negocio,
    public.cotizaciones, public.facturas to authenticated;
grant update (estado) on public.contact_messages to authenticated;
grant select (id, nombre) on public.autores to anon;
grant select (id, nombre, activo) on public.categorias to anon;
grant select (id, isbn, titulo, descripcion, precio, descuento_pct, formato, idioma,
    editorial, categoria_id, imagen_portada, activo) on public.libros to anon;
grant select (libro_id, autor_id) on public.libro_autor to anon;
grant select (libro_id, cantidad_disponible) on public.inventarios to anon;

revoke all on function private.es_admin() from public, anon;
revoke all on function private.es_personal() from public, anon;
revoke all on function private.crear_perfil_usuario() from public, anon, authenticated;

insert into storage.buckets (
    id, name, public, file_size_limit, allowed_mime_types
) values (
    'portadas', 'portadas', true, 5242880,
    array['image/jpeg', 'image/png', 'image/webp']
)
on conflict (id) do update set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

drop policy if exists portadas_admin_insertar on storage.objects;
create policy portadas_admin_insertar on storage.objects
for insert to authenticated
with check (bucket_id = 'portadas' and private.es_admin());

drop policy if exists portadas_admin_lectura on storage.objects;
create policy portadas_admin_lectura on storage.objects
for select to authenticated
using (bucket_id = 'portadas' and private.es_admin());

drop policy if exists portadas_admin_actualizar on storage.objects;
create policy portadas_admin_actualizar on storage.objects
for update to authenticated
using (bucket_id = 'portadas' and private.es_admin())
with check (bucket_id = 'portadas' and private.es_admin());

drop policy if exists portadas_admin_eliminar on storage.objects;
create policy portadas_admin_eliminar on storage.objects
for delete to authenticated
using (bucket_id = 'portadas' and private.es_admin());

create or replace function public.crear_pedido_desde_carrito(
    p_metodo_entrega text,
    p_metodo_pago text,
    p_sucursal_id bigint default null,
    p_direccion jsonb default null,
    p_notas text default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_usuario uuid := auth.uid();
    v_carrito uuid;
    v_pedido uuid;
    v_numero text;
    v_nombre text;
    v_correo text;
    v_subtotal numeric(12,2);
    v_descuento numeric(12,2);
    v_envio numeric(12,2) := 0;
    v_total numeric(12,2);
begin
    if v_usuario is null then
        raise exception 'Debes iniciar sesión para realizar un pedido.';
    end if;

    if p_metodo_entrega not in ('domicilio', 'retiro') then
        raise exception 'Método de entrega inválido.';
    end if;
    if p_metodo_pago not in ('contra_entrega', 'efectivo', 'tarjeta', 'transferencia') then
        raise exception 'Método de pago inválido.';
    end if;

    select concat_ws(' ', p.nombres, p.apellidos), u.email
      into v_nombre, v_correo
      from public.perfiles p
      join auth.users u on u.id = p.id
     where p.id = v_usuario and p.activo = true;

    if v_nombre is null then
        raise exception 'El perfil no existe o está inactivo.';
    end if;

    select c.id into v_carrito
      from public.carritos c
     where c.perfil_id = v_usuario;

    if v_carrito is null or not exists (
        select 1 from public.carrito_detalles where carrito_id = v_carrito
    ) then
        raise exception 'El carrito está vacío.';
    end if;

    -- Bloqueo de las existencias involucradas para evitar compras simultáneas.
    perform i.libro_id
      from public.inventarios i
      join public.carrito_detalles cd on cd.libro_id = i.libro_id
     where cd.carrito_id = v_carrito
     for update of i;

    if exists (
        select 1
          from public.carrito_detalles cd
          left join public.libros l on l.id = cd.libro_id
          left join public.inventarios i on i.libro_id = cd.libro_id
         where cd.carrito_id = v_carrito
           and (l.id is null or not l.activo or i.libro_id is null
                or cd.cantidad > i.cantidad_disponible)
    ) then
        raise exception 'Uno o más libros ya no tienen existencias suficientes.';
    end if;

    if p_metodo_entrega = 'retiro' then
        if p_sucursal_id is null or not exists (
            select 1 from public.sucursales
             where id = p_sucursal_id and activo = true
        ) then
            raise exception 'Selecciona una sucursal activa.';
        end if;
    else
        p_sucursal_id := null;
        if p_direccion is null
           or coalesce(btrim(p_direccion ->> 'destinatario'), '') = ''
           or coalesce(btrim(p_direccion ->> 'telefono'), '') = ''
           or coalesce(btrim(p_direccion ->> 'linea_1'), '') = ''
           or coalesce(btrim(p_direccion ->> 'ciudad'), '') = ''
           or coalesce(btrim(p_direccion ->> 'provincia'), '') = '' then
            raise exception 'La dirección de entrega está incompleta.';
        end if;

        v_envio := case
            when lower(p_direccion ->> 'provincia') in ('distrito nacional', 'santo domingo') then 150
            when lower(p_direccion ->> 'provincia') = 'santiago' then 225
            else 300
        end;
    end if;

    select sum(l.precio * cd.cantidad),
           sum(round(l.precio * cd.cantidad * l.descuento_pct / 100, 2))
      into v_subtotal, v_descuento
      from public.carrito_detalles cd
      join public.libros l on l.id = cd.libro_id
     where cd.carrito_id = v_carrito;

    v_descuento := coalesce(v_descuento, 0);
    v_total := v_subtotal - v_descuento + v_envio;

    insert into public.pedidos (
        cliente_id, cliente_nombre, cliente_correo, cliente_documento, cliente_telefono,
        metodo_entrega, sucursal_id, metodo_pago,
        subtotal, descuento, costo_envio, total, notas
    ) values (
        v_usuario, v_nombre, v_correo,
        nullif(btrim(p_direccion ->> 'documento'), ''),
        nullif(btrim(p_direccion ->> 'telefono_cliente'), ''),
        p_metodo_entrega, p_sucursal_id, p_metodo_pago,
        v_subtotal, v_descuento, v_envio, v_total, nullif(btrim(p_notas), '')
    ) returning id, numero into v_pedido, v_numero;

    insert into public.pedido_detalles (
        pedido_id, libro_id, isbn, titulo, precio_unitario, cantidad, descuento_pct
    )
    select v_pedido, l.id, l.isbn, l.titulo, l.precio, cd.cantidad, l.descuento_pct
      from public.carrito_detalles cd
      join public.libros l on l.id = cd.libro_id
     where cd.carrito_id = v_carrito;

    if p_metodo_entrega = 'domicilio' then
        insert into public.pedido_direcciones_entrega (
            pedido_id, destinatario, telefono, linea_1, linea_2,
            sector, ciudad, provincia, codigo_postal, referencia
        ) values (
            v_pedido,
            btrim(p_direccion ->> 'destinatario'),
            btrim(p_direccion ->> 'telefono'),
            btrim(p_direccion ->> 'linea_1'),
            nullif(btrim(p_direccion ->> 'linea_2'), ''),
            nullif(btrim(p_direccion ->> 'sector'), ''),
            btrim(p_direccion ->> 'ciudad'),
            btrim(p_direccion ->> 'provincia'),
            nullif(btrim(p_direccion ->> 'codigo_postal'), ''),
            nullif(btrim(p_direccion ->> 'referencia'), '')
        );
    end if;

    update public.inventarios i
       set cantidad_reservada = i.cantidad_reservada + cd.cantidad,
           actualizado_en = now()
      from public.carrito_detalles cd
     where cd.carrito_id = v_carrito
       and cd.libro_id = i.libro_id;

    insert into public.movimientos_inventario (
        libro_id, pedido_id, realizado_por, tipo,
        cambio_existencia, cambio_reservada, motivo
    )
    select cd.libro_id, v_pedido, v_usuario, 'reserva', 0, cd.cantidad,
           'Reserva automática al confirmar el pedido'
      from public.carrito_detalles cd
     where cd.carrito_id = v_carrito;

    delete from public.carrito_detalles where carrito_id = v_carrito;

    return jsonb_build_object(
        'id', v_pedido,
        'numero', v_numero,
        'subtotal', v_subtotal,
        'descuento', v_descuento,
        'costo_envio', v_envio,
        'total', v_total,
        'estado', 'pendiente',
        'estado_pago', 'pendiente'
    );
end;
$$;

revoke all on function public.crear_pedido_desde_carrito(text, text, bigint, jsonb, text)
from public, anon;

grant execute on function public.crear_pedido_desde_carrito(text, text, bigint, jsonb, text)
to authenticated;

-- Cambia el estado y mantiene las reservas del inventario consistentes.
create or replace function public.actualizar_estado_pedido(
    p_pedido_id uuid,
    p_estado text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_usuario uuid := auth.uid();
    v_estado_anterior text;
begin
    if v_usuario is null or not private.es_personal() then
        raise exception 'Acceso de personal requerido.';
    end if;
    if p_estado not in ('pendiente', 'confirmado', 'procesando', 'listo_retiro',
                        'enviado', 'entregado', 'cancelado', 'devuelto') then
        raise exception 'Estado de pedido inválido.';
    end if;

    select estado into v_estado_anterior
      from public.pedidos
     where id = p_pedido_id
     for update;
    if v_estado_anterior is null then raise exception 'Pedido no encontrado.'; end if;
    if v_estado_anterior = p_estado then return; end if;
    if not (
        (v_estado_anterior = 'pendiente' and p_estado in ('confirmado', 'procesando', 'cancelado')) or
        (v_estado_anterior = 'confirmado' and p_estado in ('procesando', 'listo_retiro', 'enviado', 'cancelado')) or
        (v_estado_anterior = 'procesando' and p_estado in ('listo_retiro', 'enviado', 'cancelado')) or
        (v_estado_anterior = 'listo_retiro' and p_estado in ('entregado', 'cancelado')) or
        (v_estado_anterior = 'enviado' and p_estado in ('entregado', 'devuelto')) or
        (v_estado_anterior = 'entregado' and p_estado = 'devuelto')
    ) then
        raise exception 'Transición de estado no permitida: % a %.', v_estado_anterior, p_estado;
    end if;

    perform i.libro_id
      from public.inventarios i
      join public.pedido_detalles pd on pd.libro_id = i.libro_id
     where pd.pedido_id = p_pedido_id
     for update of i;

    if p_estado = 'cancelado' then
        if v_estado_anterior in ('enviado', 'entregado') then
            raise exception 'Un pedido despachado debe registrarse como devuelto.';
        end if;
        if exists (
            select 1 from public.pedido_detalles pd
            join public.inventarios i on i.libro_id = pd.libro_id
            where pd.pedido_id = p_pedido_id and i.cantidad_reservada < pd.cantidad
        ) then
            raise exception 'La reserva del pedido es inconsistente.';
        end if;

        update public.inventarios i
           set cantidad_reservada = i.cantidad_reservada - pd.cantidad,
               actualizado_en = now()
          from public.pedido_detalles pd
         where pd.pedido_id = p_pedido_id and pd.libro_id = i.libro_id;

        insert into public.movimientos_inventario
            (libro_id, pedido_id, realizado_por, tipo, cambio_existencia, cambio_reservada, motivo)
        select libro_id, p_pedido_id, v_usuario, 'liberacion', 0, -cantidad,
               'Reserva liberada por cancelación del pedido'
          from public.pedido_detalles where pedido_id = p_pedido_id;
    elsif p_estado in ('enviado', 'entregado')
          and v_estado_anterior not in ('enviado', 'entregado') then
        if exists (
            select 1 from public.pedido_detalles pd
            join public.inventarios i on i.libro_id = pd.libro_id
            where pd.pedido_id = p_pedido_id
              and (i.cantidad_reservada < pd.cantidad or i.cantidad_existencia < pd.cantidad)
        ) then
            raise exception 'El inventario reservado del pedido es inconsistente.';
        end if;

        update public.inventarios i
           set cantidad_existencia = i.cantidad_existencia - pd.cantidad,
               cantidad_reservada = i.cantidad_reservada - pd.cantidad,
               actualizado_en = now()
          from public.pedido_detalles pd
         where pd.pedido_id = p_pedido_id and pd.libro_id = i.libro_id;

        insert into public.movimientos_inventario
            (libro_id, pedido_id, realizado_por, tipo, cambio_existencia, cambio_reservada, motivo)
        select libro_id, p_pedido_id, v_usuario, 'salida', -cantidad, -cantidad,
               'Salida de inventario al despachar el pedido'
          from public.pedido_detalles where pedido_id = p_pedido_id;
    elsif p_estado = 'devuelto' then
        if v_estado_anterior not in ('enviado', 'entregado') then
            raise exception 'Solo se pueden devolver pedidos enviados o entregados.';
        end if;

        update public.inventarios i
           set cantidad_existencia = i.cantidad_existencia + pd.cantidad,
               actualizado_en = now()
          from public.pedido_detalles pd
         where pd.pedido_id = p_pedido_id and pd.libro_id = i.libro_id;

        insert into public.movimientos_inventario
            (libro_id, pedido_id, realizado_por, tipo, cambio_existencia, cambio_reservada, motivo)
        select libro_id, p_pedido_id, v_usuario, 'devolucion', cantidad, 0,
               'Inventario restaurado por devolución del pedido'
          from public.pedido_detalles where pedido_id = p_pedido_id;
    end if;

    update public.pedidos
       set estado = p_estado, actualizado_en = now()
     where id = p_pedido_id;
end;
$$;

revoke all on function public.actualizar_estado_pedido(uuid, text) from public, anon;
grant execute on function public.actualizar_estado_pedido(uuid, text) to authenticated;

-- Controla los cambios del pago para impedir retrocesos o reaperturas accidentales.
create or replace function public.actualizar_pago_pedido(
    p_pedido_id uuid,
    p_estado_pago text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_estado_anterior text;
begin
    if auth.uid() is null or not private.es_personal() then
        raise exception 'Acceso de personal requerido.';
    end if;
    if p_estado_pago not in ('pendiente', 'verificando', 'pagado', 'rechazado', 'reembolsado') then
        raise exception 'Estado de pago inválido.';
    end if;

    select estado_pago into v_estado_anterior
      from public.pedidos
     where id = p_pedido_id
     for update;
    if v_estado_anterior is null then raise exception 'Pedido no encontrado.'; end if;
    if v_estado_anterior = p_estado_pago then return; end if;
    if not (
        (v_estado_anterior = 'pendiente' and p_estado_pago in ('verificando', 'pagado', 'rechazado')) or
        (v_estado_anterior = 'verificando' and p_estado_pago in ('pagado', 'rechazado')) or
        (v_estado_anterior = 'rechazado' and p_estado_pago in ('pendiente', 'verificando')) or
        (v_estado_anterior = 'pagado' and p_estado_pago = 'reembolsado')
    ) then
        raise exception 'Transición de pago no permitida: % a %.', v_estado_anterior, p_estado_pago;
    end if;

    update public.pedidos
       set estado_pago = p_estado_pago, actualizado_en = now()
     where id = p_pedido_id;
end;
$$;

revoke all on function public.actualizar_pago_pedido(uuid, text) from public, anon;
grant execute on function public.actualizar_pago_pedido(uuid, text) to authenticated;

-- Guarda los datos generales del producto y registra el inventario inicial.
create or replace function public.guardar_producto_admin(
    p_producto_id bigint,
    p_isbn text,
    p_titulo text,
    p_autor text,
    p_categoria text,
    p_editorial text,
    p_descripcion text,
    p_precio numeric,
    p_descuento_pct numeric,
    p_formato text,
    p_idioma text,
    p_imagen_portada text,
    p_stock_inicial integer,
    p_stock_minimo integer,
    p_activo boolean
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_producto_id bigint;
    v_autor_id bigint;
    v_categoria_id bigint;
begin
    if auth.uid() is null or not private.es_admin() then
        raise exception 'Acceso administrativo requerido.';
    end if;
    if coalesce(btrim(p_titulo), '') = '' then
        raise exception 'El nombre es obligatorio.';
    end if;
    if p_precio is null or p_precio < 0 then
        raise exception 'El precio no es válido.';
    end if;
    if p_descuento_pct is null or p_descuento_pct < 0 or p_descuento_pct > 100 then
        raise exception 'El descuento debe estar entre 0 y 100.';
    end if;
    if p_stock_minimo is null or p_stock_minimo < 0 then
        raise exception 'El stock mínimo no es válido.';
    end if;
    if p_formato not in ('fisico', 'digital') then
        raise exception 'El formato no es válido.';
    end if;

    if coalesce(btrim(p_categoria), '') <> '' then
        select id into v_categoria_id
          from public.categorias
         where lower(nombre) = lower(btrim(p_categoria))
         order by id
         limit 1;
        if v_categoria_id is null then
            insert into public.categorias (nombre)
            values (btrim(p_categoria))
            returning id into v_categoria_id;
        else
            update public.categorias set activo = true where id = v_categoria_id;
        end if;
    end if;

    if p_producto_id is null then
        if p_stock_inicial is null or p_stock_inicial < 0 then
            raise exception 'El inventario inicial no es válido.';
        end if;

        insert into public.libros (
            isbn, titulo, descripcion, precio, descuento_pct, formato, idioma, editorial,
            categoria_id, stock_minimo, imagen_portada, activo
        ) values (
            nullif(btrim(p_isbn), ''), btrim(p_titulo), coalesce(btrim(p_descripcion), ''),
            p_precio, p_descuento_pct, p_formato, coalesce(nullif(btrim(p_idioma), ''), 'Español'),
            nullif(btrim(p_editorial), ''), v_categoria_id, p_stock_minimo,
            nullif(btrim(p_imagen_portada), ''), coalesce(p_activo, true)
        ) returning id into v_producto_id;

        insert into public.inventarios (libro_id, cantidad_existencia)
        values (v_producto_id, p_stock_inicial);

        if p_stock_inicial > 0 then
            insert into public.movimientos_inventario (
                libro_id, realizado_por, tipo, cambio_existencia, cambio_reservada, motivo
            ) values (
                v_producto_id, auth.uid(), 'entrada', p_stock_inicial, 0, 'Inventario inicial'
            );
        end if;
    else
        update public.libros
           set isbn = nullif(btrim(p_isbn), ''),
               titulo = btrim(p_titulo),
               descripcion = coalesce(btrim(p_descripcion), ''),
               precio = p_precio,
               descuento_pct = p_descuento_pct,
               formato = p_formato,
               idioma = coalesce(nullif(btrim(p_idioma), ''), 'Español'),
               editorial = nullif(btrim(p_editorial), ''),
               categoria_id = v_categoria_id,
               stock_minimo = p_stock_minimo,
               imagen_portada = nullif(btrim(p_imagen_portada), ''),
               activo = coalesce(p_activo, true),
               actualizado_en = now()
         where id = p_producto_id
         returning id into v_producto_id;

        if v_producto_id is null then
            raise exception 'Producto no encontrado.';
        end if;
    end if;

    delete from public.libro_autor where libro_id = v_producto_id;
    if coalesce(btrim(p_autor), '') <> '' then
        select id into v_autor_id
          from public.autores
         where lower(nombre) = lower(btrim(p_autor))
         order by id
         limit 1;
        if v_autor_id is null then
            insert into public.autores (nombre)
            values (btrim(p_autor))
            returning id into v_autor_id;
        end if;

        insert into public.libro_autor (libro_id, autor_id)
        values (v_producto_id, v_autor_id);
    end if;

    return v_producto_id;
end;
$$;

-- Elimina productos sin actividad; los demás quedan desactivados para conservar el historial.
create or replace function public.eliminar_producto_admin(p_producto_id bigint)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_tiene_historial boolean;
begin
    if auth.uid() is null or not private.es_admin() then
        raise exception 'Acceso administrativo requerido.';
    end if;

    select exists (
        select 1 from public.pedido_detalles where libro_id = p_producto_id
        union all
        select 1 from public.movimientos_inventario where libro_id = p_producto_id
    ) into v_tiene_historial;

    if v_tiene_historial then
        update public.libros set activo = false, actualizado_en = now()
         where id = p_producto_id;
        if not found then raise exception 'Producto no encontrado.'; end if;
        return 'desactivado';
    end if;

    delete from public.libros where id = p_producto_id;
    if not found then raise exception 'Producto no encontrado.'; end if;
    return 'eliminado';
end;
$$;

-- Registra entradas, salidas y conteos físicos sin permitir existencias negativas.
create or replace function public.ajustar_inventario_admin(
    p_producto_id bigint,
    p_tipo text,
    p_cantidad integer,
    p_motivo text
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_actual integer;
    v_reservada integer;
    v_nueva integer;
    v_cambio integer;
begin
    if auth.uid() is null or not private.es_personal() then
        raise exception 'Acceso de personal requerido.';
    end if;
    if p_tipo not in ('entrada', 'salida', 'ajuste') then
        raise exception 'Tipo de movimiento inválido.';
    end if;
    if p_cantidad is null or p_cantidad < 0 or (p_tipo <> 'ajuste' and p_cantidad = 0) then
        raise exception 'Cantidad inválida.';
    end if;
    if coalesce(btrim(p_motivo), '') = '' then
        raise exception 'El motivo es obligatorio.';
    end if;

    select cantidad_existencia, cantidad_reservada
      into v_actual, v_reservada
      from public.inventarios
     where libro_id = p_producto_id
     for update;
    if v_actual is null then raise exception 'Inventario no encontrado.'; end if;

    v_nueva := case p_tipo
        when 'entrada' then v_actual + p_cantidad
        when 'salida' then v_actual - p_cantidad
        else p_cantidad
    end;
    if v_nueva < v_reservada then
        raise exception 'La existencia no puede ser menor que la cantidad reservada.';
    end if;
    v_cambio := v_nueva - v_actual;
    if v_cambio = 0 then raise exception 'El ajuste no produce ningún cambio.'; end if;

    update public.inventarios
       set cantidad_existencia = v_nueva, actualizado_en = now()
     where libro_id = p_producto_id;

    insert into public.movimientos_inventario (
        libro_id, realizado_por, tipo, cambio_existencia, cambio_reservada, motivo
    ) values (
        p_producto_id, auth.uid(), p_tipo, v_cambio, 0, btrim(p_motivo)
    );

    return jsonb_build_object(
        'cantidad_existencia', v_nueva,
        'cantidad_reservada', v_reservada,
        'cantidad_disponible', v_nueva - v_reservada
    );
end;
$$;

-- Muestra el historial de inventario al personal sin abrir los perfiles de otros usuarios.
create or replace function public.listar_movimientos_inventario(p_limite integer default 40)
returns table (
    id bigint,
    producto text,
    tipo text,
    cambio_existencia integer,
    cambio_reservada integer,
    motivo text,
    responsable text,
    creado_en timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null or not private.es_personal() then
        raise exception 'Acceso de personal requerido.';
    end if;

    return query
    select m.id::bigint,
           l.titulo::text,
           m.tipo::text,
           m.cambio_existencia::integer,
           m.cambio_reservada::integer,
           m.motivo::text,
           nullif(btrim(concat_ws(' ', p.nombres, p.apellidos)), '')::text,
           m.creado_en::timestamptz
      from public.movimientos_inventario m
      join public.libros l on l.id = m.libro_id
      left join public.perfiles p on p.id = m.realizado_por
     order by m.creado_en desc
     limit least(greatest(coalesce(p_limite, 40), 1), 200);
end;
$$;

-- Devuelve usuarios y roles sin exponer contraseñas ni tokens.
create or replace function public.listar_usuarios_admin()
returns table (
    id uuid,
    correo text,
    nombres text,
    apellidos text,
    activo boolean,
    rol text,
    creado_en timestamptz
)
language plpgsql
stable
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null or not private.es_admin() then
        raise exception 'Acceso administrativo requerido.';
    end if;

    return query
    select p.id::uuid, u.email::text, p.nombres::text, p.apellidos::text, p.activo::boolean,
           coalesce(r.codigo::text, 'cliente'::text), p.creado_en::timestamptz
      from public.perfiles p
      join auth.users u on u.id = p.id
      left join public.usuario_roles ur on ur.usuario_id = p.id
      left join public.roles r on r.id = ur.rol_id
     order by p.creado_en desc;
end;
$$;

create or replace function public.actualizar_usuario_admin(
    p_usuario_id uuid,
    p_nombres text,
    p_apellidos text,
    p_activo boolean,
    p_rol text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_rol_id smallint;
begin
    if auth.uid() is null or not private.es_admin() then
        raise exception 'Acceso administrativo requerido.';
    end if;
    if p_usuario_id = auth.uid() and (not p_activo or p_rol <> 'administrador') then
        raise exception 'No puedes retirar tu propio acceso administrativo.';
    end if;
    if coalesce(btrim(p_nombres), '') = '' then
        raise exception 'El nombre es obligatorio.';
    end if;

    select id into v_rol_id from public.roles where codigo = p_rol;
    if v_rol_id is null then raise exception 'Rol inválido.'; end if;

    update public.perfiles
       set nombres = btrim(p_nombres),
           apellidos = coalesce(btrim(p_apellidos), ''),
           activo = p_activo,
           actualizado_en = now()
     where id = p_usuario_id;
    if not found then raise exception 'Usuario no encontrado.'; end if;

    insert into public.usuario_roles (usuario_id, rol_id)
    values (p_usuario_id, v_rol_id)
    on conflict (usuario_id) do update set rol_id = excluded.rol_id, asignado_en = now();
end;
$$;

revoke all on function public.guardar_producto_admin(
    bigint, text, text, text, text, text, text, numeric, numeric, text, text, text,
    integer, integer, boolean
) from public, anon;
revoke all on function public.eliminar_producto_admin(bigint) from public, anon;
revoke all on function public.ajustar_inventario_admin(bigint, text, integer, text) from public, anon;
revoke all on function public.listar_movimientos_inventario(integer) from public, anon;
revoke all on function public.listar_usuarios_admin() from public, anon;
revoke all on function public.actualizar_usuario_admin(uuid, text, text, boolean, text)
from public, anon;

grant execute on function public.guardar_producto_admin(
    bigint, text, text, text, text, text, text, numeric, numeric, text, text, text,
    integer, integer, boolean
) to authenticated;
grant execute on function public.eliminar_producto_admin(bigint) to authenticated;
grant execute on function public.ajustar_inventario_admin(bigint, text, integer, text)
to authenticated;
grant execute on function public.listar_movimientos_inventario(integer) to authenticated;
grant execute on function public.listar_usuarios_admin() to authenticated;
grant execute on function public.actualizar_usuario_admin(uuid, text, text, boolean, text)
to authenticated;

create or replace function public.guardar_categoria_admin(
    p_categoria_id bigint,
    p_nombre text,
    p_activo boolean
)
returns bigint
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_categoria_id bigint;
begin
    if auth.uid() is null or not private.es_admin() then
        raise exception 'Acceso administrativo requerido.';
    end if;
    if coalesce(btrim(p_nombre), '') = '' then
        raise exception 'El nombre de la categoría es obligatorio.';
    end if;
    if exists (
        select 1 from public.categorias
         where lower(nombre) = lower(btrim(p_nombre))
           and id <> coalesce(p_categoria_id, -1)
    ) then
        raise exception 'Ya existe una categoría con ese nombre.';
    end if;

    if p_categoria_id is null then
        insert into public.categorias (nombre, activo)
        values (btrim(p_nombre), coalesce(p_activo, true))
        returning id into v_categoria_id;
    else
        update public.categorias
           set nombre = btrim(p_nombre), activo = coalesce(p_activo, true)
         where id = p_categoria_id
        returning id into v_categoria_id;
        if v_categoria_id is null then raise exception 'Categoría no encontrada.'; end if;
    end if;

    return v_categoria_id;
end;
$$;

create or replace function public.eliminar_categoria_admin(p_categoria_id bigint)
returns text
language plpgsql
security definer
set search_path = ''
as $$
begin
    if auth.uid() is null or not private.es_admin() then
        raise exception 'Acceso administrativo requerido.';
    end if;

    if exists (select 1 from public.libros where categoria_id = p_categoria_id) then
        update public.categorias set activo = false where id = p_categoria_id;
        if not found then raise exception 'Categoría no encontrada.'; end if;
        return 'desactivada';
    end if;

    delete from public.categorias where id = p_categoria_id;
    if not found then raise exception 'Categoría no encontrada.'; end if;
    return 'eliminada';
end;
$$;

revoke all on function public.guardar_categoria_admin(bigint, text, boolean) from public, anon;
revoke all on function public.eliminar_categoria_admin(bigint) from public, anon;
grant execute on function public.guardar_categoria_admin(bigint, text, boolean) to authenticated;
grant execute on function public.eliminar_categoria_admin(bigint) to authenticated;

create or replace function public.enviar_mensaje_contacto(
    p_nombre text,
    p_correo text,
    p_asunto text,
    p_mensaje text,
    p_telefono text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_id uuid;
    v_user_id uuid := auth.uid();
    v_nombre text := btrim(coalesce(p_nombre, ''));
    v_correo text := lower(btrim(coalesce(p_correo, '')));
    v_asunto text := btrim(coalesce(p_asunto, ''));
    v_mensaje text := btrim(coalesce(p_mensaje, ''));
    v_telefono text := nullif(btrim(coalesce(p_telefono, '')), '');
begin
    if char_length(v_nombre) not between 3 and 160 then
        raise exception 'El nombre debe tener entre 3 y 160 caracteres.';
    end if;
    if char_length(v_correo) > 320
       or v_correo !~* '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$' then
        raise exception 'El correo electrónico no es válido.';
    end if;
    if char_length(v_asunto) not between 3 and 160 then
        raise exception 'El asunto debe tener entre 3 y 160 caracteres.';
    end if;
    if char_length(v_mensaje) not between 10 and 5000 then
        raise exception 'El mensaje debe tener entre 10 y 5000 caracteres.';
    end if;
    if v_telefono is not null and char_length(v_telefono) > 25 then
        raise exception 'El teléfono es demasiado largo.';
    end if;
    if v_user_id is not null and not exists (
        select 1 from public.perfiles
        where id = v_user_id and activo
    ) then
        raise exception 'La cuenta no está activa.';
    end if;

    insert into public.contact_messages (
        user_id, nombre, correo, telefono, asunto, mensaje
    ) values (
        v_user_id, v_nombre, v_correo, v_telefono, v_asunto, v_mensaje
    )
    returning id into v_id;

    return v_id;
end;
$$;

revoke all on function public.enviar_mensaje_contacto(text, text, text, text, text)
from public;
grant execute on function public.enviar_mensaje_contacto(text, text, text, text, text)
to anon, authenticated;

revoke insert on public.contact_messages from anon, authenticated;

create or replace function private.snapshot_documento_pedido(
    p_pedido_id uuid,
    p_tipo text,
    p_numero text,
    p_fecha_emision date,
    p_fecha_limite date default null,
    p_ncf text default null,
    p_condicion_pago text default null,
    p_notas text default null,
    p_creado_por uuid default null
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_pedido public.pedidos%rowtype;
    v_config public.configuracion_negocio%rowtype;
    v_articulos jsonb;
    v_entrega jsonb;
    v_sucursal jsonb;
    v_atendido_por text;
    v_mostrar_itbis boolean;
    v_itbis_pct numeric(5,2);
    v_itbis numeric(12,2);
begin
    if p_tipo not in ('cotizacion', 'factura') then
        raise exception 'Tipo de documento invalido.';
    end if;

    select * into v_pedido
      from public.pedidos
     where id = p_pedido_id;

    if not found then
        raise exception 'Pedido no encontrado.';
    end if;

    select * into v_config
      from public.configuracion_negocio
     where id = 1;

    select coalesce(
        jsonb_agg(
            jsonb_build_object(
                'libro_id', pd.libro_id,
                'isbn', pd.isbn,
                'descripcion', pd.titulo,
                'cantidad', pd.cantidad,
                'precio_unitario', pd.precio_unitario,
                'descuento_pct', pd.descuento_pct,
                'descuento', pd.descuento,
                'total', pd.total_linea
            ) order by pd.libro_id
        ),
        '[]'::jsonb
    ) into v_articulos
      from public.pedido_detalles pd
     where pd.pedido_id = p_pedido_id;

    select to_jsonb(d) into v_entrega
      from public.pedido_direcciones_entrega d
     where d.pedido_id = p_pedido_id;

    select jsonb_build_object(
        'nombre', s.nombre,
        'direccion', s.direccion,
        'ciudad', s.ciudad,
        'provincia', s.provincia,
        'telefono', s.telefono
    ) into v_sucursal
      from public.sucursales s
     where s.id = v_pedido.sucursal_id;

    select nullif(btrim(concat_ws(' ', p.nombres, p.apellidos)), '')
      into v_atendido_por
      from public.perfiles p
      join public.usuario_roles ur on ur.usuario_id = p.id
      join public.roles r on r.id = ur.rol_id and r.codigo in ('administrador', 'empleado')
     where p.id = p_creado_por;

    v_atendido_por := coalesce(v_atendido_por, nullif(v_config.atendido_por_default, ''), 'Libreria Quisqueya');
    v_mostrar_itbis := case when p_tipo = 'cotizacion' then v_config.cotizacion_mostrar_itbis else v_config.factura_mostrar_itbis end;
    v_itbis_pct := case when p_tipo = 'cotizacion' then v_config.cotizacion_itbis_pct else v_config.factura_itbis_pct end;

    -- El pedido ya contiene el precio final. El ITBIS se presenta incluido para no alterar su total.
    v_itbis := case
        when v_mostrar_itbis and v_itbis_pct > 0
        then round((v_pedido.subtotal - v_pedido.descuento) * v_itbis_pct / (100 + v_itbis_pct), 2)
        else 0
    end;

    return jsonb_build_object(
        'version', 1,
        'tipo', p_tipo,
        'empresa', jsonb_build_object(
            'nombre_comercial', v_config.nombre_comercial,
            'razon_social', v_config.razon_social,
            'eslogan', v_config.eslogan,
            'rnc', v_config.rnc,
            'direccion', v_config.direccion,
            'ciudad', v_config.ciudad,
            'provincia', v_config.provincia,
            'pais', v_config.pais,
            'telefono', v_config.telefono,
            'correo', v_config.correo,
            'sitio_web', v_config.sitio_web,
            'logo_url', v_config.logo_url
        ),
        'documento', jsonb_build_object(
            'numero', p_numero,
            'fecha_emision', p_fecha_emision,
            'fecha_limite', p_fecha_limite,
            'ncf', p_ncf,
            'condicion_pago', p_condicion_pago,
            'metodo_pago', v_pedido.metodo_pago,
            'atendido_por', v_atendido_por,
            'tiempo_entrega', case when p_tipo = 'cotizacion' then v_config.cotizacion_tiempo_entrega else null end,
            'condiciones', case when p_tipo = 'cotizacion' then v_config.cotizacion_condiciones else v_config.factura_condiciones end,
            'notas', coalesce(p_notas, case when p_tipo = 'cotizacion' then v_config.cotizacion_notas else v_config.factura_notas end),
            'mostrar_itbis', v_mostrar_itbis,
            'itbis_pct', v_itbis_pct
        ),
        'pedido', jsonb_build_object(
            'id', v_pedido.id,
            'numero', v_pedido.numero,
            'metodo_entrega', v_pedido.metodo_entrega,
            'notas', v_pedido.notas
        ),
        'cliente', jsonb_build_object(
            'id', v_pedido.cliente_id,
            'nombre', v_pedido.cliente_nombre,
            'correo', v_pedido.cliente_correo,
            'telefono', coalesce(v_pedido.cliente_telefono, v_entrega ->> 'telefono'),
            'documento', v_pedido.cliente_documento,
            'direccion', case
                when v_pedido.metodo_entrega = 'domicilio' then concat_ws(', ',
                    nullif(v_entrega ->> 'linea_1', ''),
                    nullif(v_entrega ->> 'linea_2', ''),
                    nullif(v_entrega ->> 'sector', ''),
                    nullif(v_entrega ->> 'ciudad', ''),
                    nullif(v_entrega ->> 'provincia', '')
                )
                else concat_ws(', ', v_sucursal ->> 'direccion', v_sucursal ->> 'ciudad', v_sucursal ->> 'provincia')
            end
        ),
        'entrega', coalesce(v_entrega, v_sucursal, '{}'::jsonb),
        'articulos', v_articulos,
        'totales', jsonb_build_object(
            'subtotal', v_pedido.subtotal,
            'descuento', v_pedido.descuento,
            'itbis', v_itbis,
            'costo_envio', v_pedido.costo_envio,
            'total', v_pedido.total
        )
    );
end;
$$;

create or replace function private.crear_cotizacion_pedido(
    p_pedido_id uuid,
    p_creado_por uuid default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_existente uuid;
    v_pedido public.pedidos%rowtype;
    v_config public.configuracion_negocio%rowtype;
    v_id uuid;
    v_numero text;
    v_fecha date := current_date;
    v_valida_hasta date;
    v_snapshot jsonb;
begin
    perform pg_advisory_xact_lock(hashtextextended('cotizacion:' || p_pedido_id::text, 0));

    select id into v_existente from public.cotizaciones where pedido_id = p_pedido_id;
    if v_existente is not null then return v_existente; end if;

    select * into v_pedido from public.pedidos where id = p_pedido_id;
    if not found then raise exception 'Pedido no encontrado.'; end if;

    select * into v_config from public.configuracion_negocio where id = 1;
    v_numero := upper(v_config.cotizacion_prefijo) || '-' || lpad(nextval('public.cotizaciones_numero_seq')::text, 4, '0');
    v_valida_hasta := v_fecha + v_config.cotizacion_validez_dias;
    v_snapshot := private.snapshot_documento_pedido(
        p_pedido_id, 'cotizacion', v_numero, v_fecha, v_valida_hasta,
        null, null, null, p_creado_por
    );

    insert into public.cotizaciones (
        numero, pedido_id, cliente_id, fecha_emision, valida_hasta,
        subtotal, descuento, itbis, total, snapshot, creado_por
    ) values (
        v_numero, p_pedido_id, v_pedido.cliente_id, v_fecha, v_valida_hasta,
        v_pedido.subtotal, v_pedido.descuento, (v_snapshot #>> '{totales,itbis}')::numeric,
        v_pedido.total, v_snapshot, p_creado_por
    ) returning id into v_id;

    return v_id;
end;
$$;

create or replace function private.cotizar_pedido_al_confirmar()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    perform private.crear_cotizacion_pedido(new.id, new.cliente_id);
    return new;
end;
$$;

drop trigger if exists crear_cotizacion_al_confirmar_pedido on public.pedidos;
create constraint trigger crear_cotizacion_al_confirmar_pedido
after insert on public.pedidos
deferrable initially deferred
for each row execute function private.cotizar_pedido_al_confirmar();

create or replace function private.sincronizar_estado_documentos()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
    if new.estado = 'cancelado' and old.estado <> 'cancelado' then
        update public.cotizaciones set estado = 'anulada' where pedido_id = new.id and estado <> 'anulada';
        update public.facturas set estado = 'anulada' where pedido_id = new.id and estado <> 'anulada';
    end if;
    return new;
end;
$$;

drop trigger if exists sincronizar_documentos_al_cambiar_pedido on public.pedidos;
create trigger sincronizar_documentos_al_cambiar_pedido
after update of estado on public.pedidos
for each row execute function private.sincronizar_estado_documentos();

create or replace function public.generar_factura_pedido(
    p_pedido_id uuid,
    p_ncf text default null,
    p_condicion_pago text default null,
    p_fecha_vencimiento date default null,
    p_notas text default null
)
returns public.facturas
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_usuario uuid := auth.uid();
    v_existente public.facturas%rowtype;
    v_pedido public.pedidos%rowtype;
    v_config public.configuracion_negocio%rowtype;
    v_factura public.facturas%rowtype;
    v_numero text;
    v_fecha date := current_date;
    v_condicion text;
    v_ncf text := upper(nullif(btrim(p_ncf), ''));
    v_snapshot jsonb;
begin
    if v_usuario is null or not private.es_personal() then
        raise exception 'Acceso de personal requerido.';
    end if;

    perform pg_advisory_xact_lock(hashtextextended('factura:' || p_pedido_id::text, 0));
    select * into v_existente from public.facturas where pedido_id = p_pedido_id;
    if found then return v_existente; end if;

    select * into v_pedido from public.pedidos where id = p_pedido_id for update;
    if not found then raise exception 'Pedido no encontrado.'; end if;
    if v_pedido.estado not in ('procesando', 'listo_retiro', 'enviado', 'entregado') then
        raise exception 'La factura solo puede generarse cuando el pedido esta listo para procesarse o entregarse.';
    end if;

    select * into v_config from public.configuracion_negocio where id = 1;
    v_condicion := coalesce(nullif(p_condicion_pago, ''), v_config.factura_condicion_pago);
    if v_condicion not in ('contado', 'credito') then
        raise exception 'Condicion de pago invalida.';
    end if;
    if v_condicion = 'credito' then
        p_fecha_vencimiento := coalesce(p_fecha_vencimiento, v_fecha + v_config.factura_dias_credito);
        if p_fecha_vencimiento < v_fecha then raise exception 'La fecha de vencimiento no puede ser anterior a la emision.'; end if;
    else
        p_fecha_vencimiento := null;
    end if;

    v_numero := upper(v_config.factura_prefijo) || '-' || lpad(nextval('public.facturas_numero_seq')::text, 4, '0');
    v_snapshot := private.snapshot_documento_pedido(
        p_pedido_id, 'factura', v_numero, v_fecha, p_fecha_vencimiento,
        v_ncf, v_condicion, nullif(btrim(p_notas), ''), v_usuario
    );

    insert into public.facturas (
        numero, pedido_id, cliente_id, ncf, fecha_emision, fecha_vencimiento,
        condicion_pago, subtotal, descuento, itbis, total, snapshot, creado_por
    ) values (
        v_numero, p_pedido_id, v_pedido.cliente_id, v_ncf, v_fecha, p_fecha_vencimiento,
        v_condicion, v_pedido.subtotal, v_pedido.descuento, (v_snapshot #>> '{totales,itbis}')::numeric,
        v_pedido.total, v_snapshot, v_usuario
    ) returning * into v_factura;

    return v_factura;
exception
    when unique_violation then
        if v_ncf is not null and exists (select 1 from public.facturas where ncf = v_ncf) then
            raise exception 'El NCF indicado ya esta asociado a otra factura.';
        end if;
        select * into v_factura from public.facturas where pedido_id = p_pedido_id;
        if found then return v_factura; end if;
        raise;
end;
$$;

create or replace function public.guardar_configuracion_negocio(p_datos jsonb)
returns public.configuracion_negocio
language plpgsql
security definer
set search_path = ''
as $$
declare
    v_resultado public.configuracion_negocio%rowtype;
    v_cot_prefijo text := upper(coalesce(nullif(btrim(p_datos ->> 'cotizacion_prefijo'), ''), 'COT'));
    v_fac_prefijo text := upper(coalesce(nullif(btrim(p_datos ->> 'factura_prefijo'), ''), 'FAC'));
begin
    if auth.uid() is null or not private.es_admin() then
        raise exception 'Acceso de administrador requerido.';
    end if;
    if v_cot_prefijo !~ '^[A-Z0-9]{2,8}$' or v_fac_prefijo !~ '^[A-Z0-9]{2,8}$' then
        raise exception 'Los prefijos deben tener entre 2 y 8 letras o numeros.';
    end if;

    update public.configuracion_negocio set
        nombre_comercial = coalesce(nullif(btrim(p_datos ->> 'nombre_comercial'), ''), nombre_comercial),
        razon_social = coalesce(nullif(btrim(p_datos ->> 'razon_social'), ''), razon_social),
        eslogan = nullif(btrim(p_datos ->> 'eslogan'), ''),
        rnc = nullif(btrim(p_datos ->> 'rnc'), ''),
        direccion = nullif(btrim(p_datos ->> 'direccion'), ''),
        ciudad = nullif(btrim(p_datos ->> 'ciudad'), ''),
        provincia = nullif(btrim(p_datos ->> 'provincia'), ''),
        pais = coalesce(nullif(btrim(p_datos ->> 'pais'), ''), pais),
        telefono = nullif(btrim(p_datos ->> 'telefono'), ''),
        correo = nullif(btrim(p_datos ->> 'correo'), ''),
        sitio_web = nullif(btrim(p_datos ->> 'sitio_web'), ''),
        logo_url = coalesce(nullif(btrim(p_datos ->> 'logo_url'), ''), logo_url),
        atendido_por_default = nullif(btrim(p_datos ->> 'atendido_por_default'), ''),
        cotizacion_prefijo = v_cot_prefijo,
        cotizacion_validez_dias = coalesce((p_datos ->> 'cotizacion_validez_dias')::integer, cotizacion_validez_dias),
        cotizacion_tiempo_entrega = nullif(btrim(p_datos ->> 'cotizacion_tiempo_entrega'), ''),
        cotizacion_condiciones = nullif(btrim(p_datos ->> 'cotizacion_condiciones'), ''),
        cotizacion_notas = nullif(btrim(p_datos ->> 'cotizacion_notas'), ''),
        cotizacion_mostrar_itbis = coalesce((p_datos ->> 'cotizacion_mostrar_itbis')::boolean, cotizacion_mostrar_itbis),
        cotizacion_itbis_pct = coalesce((p_datos ->> 'cotizacion_itbis_pct')::numeric, cotizacion_itbis_pct),
        factura_prefijo = v_fac_prefijo,
        factura_condicion_pago = coalesce(nullif(p_datos ->> 'factura_condicion_pago', ''), factura_condicion_pago),
        factura_dias_credito = coalesce((p_datos ->> 'factura_dias_credito')::integer, factura_dias_credito),
        factura_condiciones = nullif(btrim(p_datos ->> 'factura_condiciones'), ''),
        factura_notas = nullif(btrim(p_datos ->> 'factura_notas'), ''),
        factura_mostrar_itbis = coalesce((p_datos ->> 'factura_mostrar_itbis')::boolean, factura_mostrar_itbis),
        factura_itbis_pct = coalesce((p_datos ->> 'factura_itbis_pct')::numeric, factura_itbis_pct),
        actualizado_por = auth.uid(),
        actualizado_en = now()
    where id = 1
    returning * into v_resultado;

    return v_resultado;
end;
$$;

revoke all on function public.generar_factura_pedido(uuid, text, text, date, text) from public, anon;
grant execute on function public.generar_factura_pedido(uuid, text, text, date, text) to authenticated;

revoke all on function public.guardar_configuracion_negocio(jsonb) from public, anon;
grant execute on function public.guardar_configuracion_negocio(jsonb) to authenticated;

revoke all on function private.snapshot_documento_pedido(uuid, text, text, date, date, text, text, text, uuid) from public, anon, authenticated;
revoke all on function private.crear_cotizacion_pedido(uuid, uuid) from public, anon, authenticated;
revoke all on function private.cotizar_pedido_al_confirmar() from public, anon, authenticated;
revoke all on function private.sincronizar_estado_documentos() from public, anon, authenticated;

insert into public.categorias (nombre)
select datos.nombre
from (values
    ('Novela'), ('Clásicos'), ('Literatura infantil'), ('Ciencia ficción')
) as datos(nombre)
where not exists (
    select 1 from public.categorias c where lower(c.nombre) = lower(datos.nombre)
);

insert into public.autores (nombre)
select datos.nombre
from (values
    ('George Orwell'), ('Antoine de Saint-Exupéry'),
    ('Miguel de Cervantes'), ('Gabriel García Márquez')
) as datos(nombre)
where not exists (
    select 1 from public.autores a where lower(a.nombre) = lower(datos.nombre)
);

insert into public.libros (
    isbn, titulo, descripcion, precio, formato, idioma, editorial,
    categoria_id, stock_minimo, imagen_portada, activo
)
select datos.isbn, datos.titulo, datos.descripcion, datos.precio,
       'fisico', 'Español', datos.editorial, c.id,
       datos.stock_minimo, datos.imagen, true
from (values
    ('9780451524935', '1984', 'Una novela sobre vigilancia, poder y libertad individual.', 850.00, 'Debolsillo', 4, 'assets/portadas/1984.jpg', 'Ciencia ficción'),
    ('9780156012195', 'El Principito', 'Un relato sobre la amistad, el crecimiento y lo verdaderamente importante.', 750.00, 'Salamandra', 4, 'assets/portadas/el-principito.jpg', 'Literatura infantil'),
    ('9788420412146', 'Don Quijote de la Mancha', 'Las aventuras de don Quijote y Sancho Panza.', 1350.00, 'Alfaguara', 3, 'assets/portadas/don-quijote.jpg', 'Clásicos'),
    ('9780307474728', 'Cien años de soledad', 'La historia de la familia Buendía y el pueblo de Macondo.', 1100.00, 'Vintage Español', 3, 'assets/portadas/cien-anos-de-soledad.jpg', 'Novela')
) as datos(isbn, titulo, descripcion, precio, editorial, stock_minimo, imagen, categoria)
join lateral (
    select id from public.categorias
    where lower(nombre) = lower(datos.categoria)
    order by id limit 1
) c on true
where not exists (
    select 1 from public.libros l where l.isbn = datos.isbn
);

insert into public.libro_autor (libro_id, autor_id)
select l.id, a.id
from (values
    ('9780451524935', 'George Orwell'),
    ('9780156012195', 'Antoine de Saint-Exupéry'),
    ('9788420412146', 'Miguel de Cervantes'),
    ('9780307474728', 'Gabriel García Márquez')
) as datos(isbn, autor)
join lateral (
    select id from public.libros where isbn = datos.isbn order by id limit 1
) l on true
join lateral (
    select id from public.autores
    where lower(nombre) = lower(datos.autor) order by id limit 1
) a on true
where not exists (
    select 1 from public.libro_autor la
    where la.libro_id = l.id and la.autor_id = a.id
);

with inventario_nuevo as (
    insert into public.inventarios (libro_id, cantidad_existencia)
    select l.id, datos.cantidad
    from (values
        ('9780451524935', 12),
        ('9780156012195', 10),
        ('9788420412146', 7),
        ('9780307474728', 5)
    ) as datos(isbn, cantidad)
    join lateral (
        select id from public.libros where isbn = datos.isbn order by id limit 1
    ) l on true
    where not exists (
        select 1 from public.inventarios i where i.libro_id = l.id
    )
    returning libro_id, cantidad_existencia
)
insert into public.movimientos_inventario (
    libro_id, realizado_por, tipo, cambio_existencia, cambio_reservada, motivo
)
select libro_id, null, 'entrada', cantidad_existencia, 0,
       'Inventario inicial'
from inventario_nuevo
where cantidad_existencia > 0;

notify pgrst, 'reload schema';



commit;
